name: Kazakh Transliteration API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install
    
    - name: Run tests
      run: ruby test_app.rb
    
    - name: Test API endpoints
      run: |
        bundle exec ruby app.rb &
        sleep 3
        
        # Test health endpoint
        curl -f http://localhost:4567/health
        
        # Test transliteration
        curl -X POST -H "Content-Type: application/json" \
             -d '{"text":"Сәлем әлем"}' \
             http://localhost:4567/transliterate